# Generated by Django 5.2.16 on 2026-07-27 20:26

import django.db.models.deletion
import procesamientos.models
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GastoProcesamientoDimanno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(choices=[('comision', 'Comisión'), ('flete_eu', 'Flete Eu'), ('control_calidad_eu', 'Control calidad Eu'), ('thc', 'THC'), ('transporte', 'Transporte'), ('aduanas', 'Aduanas')], max_length=40)),
                ('nombre', models.CharField(max_length=100)),
                ('orden', models.PositiveSmallIntegerField()),
                ('valor_original', models.DecimalField(decimal_places=6, max_digits=18)),
                ('valor_aplicado', models.DecimalField(decimal_places=6, max_digits=18)),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='ProcesamientoDimanno',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('anio', models.PositiveIntegerField()),
                ('nombre_hoja', models.CharField(max_length=100)),
                ('factura_corta', models.CharField(max_length=20)),
                ('semana', models.PositiveIntegerField()),
                ('estado', models.CharField(max_length=40)),
                ('destino_liquidacion', models.CharField(blank=True, max_length=150)),
                ('destinos_despachos', models.JSONField(blank=True, default=list)),
                ('destino_final', models.CharField(blank=True, max_length=150)),
                ('cantidad_contenedores', models.PositiveIntegerField(default=0)),
                ('total_cajas_liquidacion', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=18)),
                ('total_cajas_despachos', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=18)),
                ('puede_escribir', models.BooleanField(default=False)),
                ('requiere_resolver_destino', models.BooleanField(default=False)),
                ('errores', models.JSONField(blank=True, default=list)),
                ('advertencias', models.JSONField(blank=True, default=list)),
                ('lineas_preparadas', models.JSONField(blank=True, default=list)),
                ('archivo_despachos', models.FileField(upload_to=procesamientos.models.ruta_archivo_despachos)),
                ('archivo_liquidacion', models.FileField(upload_to=procesamientos.models.ruta_archivo_liquidacion)),
                ('archivo_cliente', models.FileField(upload_to=procesamientos.models.ruta_archivo_cliente)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='CorreccionGastoDimanno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_anterior', models.DecimalField(decimal_places=6, max_digits=18)),
                ('valor_nuevo', models.DecimalField(decimal_places=6, max_digits=18)),
                ('motivo', models.TextField()),
                ('usuario_nombre', models.CharField(max_length=150)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('gasto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correcciones', to='procesamientos.gastoprocesamientodimanno')),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
        migrations.AddField(
            model_name='gastoprocesamientodimanno',
            name='procesamiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gastos', to='procesamientos.procesamientodimanno'),
        ),
        migrations.AddConstraint(
            model_name='gastoprocesamientodimanno',
            constraint=models.UniqueConstraint(fields=('procesamiento', 'codigo'), name='uniq_gasto_dimanno_procesamiento_codigo'),
        ),
    ]
