# Generated by Django 5.2.16 on 2026-07-27 20:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procesamientos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='procesamientodimanno',
            name='origen_destino_final',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.CreateModel(
            name='ResolucionDestinoDimanno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destino_anterior', models.CharField(blank=True, max_length=150)),
                ('destino_nuevo', models.CharField(max_length=150)),
                ('origen_seleccionado', models.CharField(choices=[('liquidacion', 'Liquidación'), ('despachos', 'Despachos'), ('manual', 'Manual')], max_length=30)),
                ('destino_liquidacion', models.CharField(blank=True, max_length=150)),
                ('destinos_despachos', models.JSONField(blank=True, default=list)),
                ('motivo', models.TextField()),
                ('usuario_nombre', models.CharField(max_length=150)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('procesamiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resoluciones_destino', to='procesamientos.procesamientodimanno')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
    ]
