# Generated by Django 5.2.16 on 2026-07-27 21:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procesamientos', '0002_origen_destino_y_resolucion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='procesamientodimanno',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procesamientos_dimanno_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='procesamientodimanno',
            name='creado_por_nombre',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
