# Generated by Django 5.2.16 on 2026-07-27 22:27

import django.db.models.deletion
import procesamientos.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procesamientos', '0003_creado_por_usuario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneracionDimanno',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('procesando', 'Procesando'), ('completado', 'Completado'), ('error', 'Error')], default='pendiente', max_length=20)),
                ('solicitado_por_nombre', models.CharField(max_length=150)),
                ('solicitado_en', models.DateTimeField(auto_now_add=True)),
                ('iniciado_en', models.DateTimeField(blank=True, null=True)),
                ('finalizado_en', models.DateTimeField(blank=True, null=True)),
                ('archivo_resultado', models.FileField(blank=True, upload_to=procesamientos.models.ruta_archivo_resultado_generacion)),
                ('nombre_descarga', models.CharField(blank=True, max_length=255)),
                ('mensaje_error', models.TextField(blank=True)),
                ('destino_aplicado', models.CharField(max_length=150)),
                ('origen_destino_aplicado', models.CharField(blank=True, max_length=30)),
                ('gastos_aplicados', models.JSONField(default=dict)),
                ('filas_agregadas', models.PositiveIntegerField(blank=True, null=True)),
                ('fila_inicial', models.PositiveIntegerField(blank=True, null=True)),
                ('fila_final', models.PositiveIntegerField(blank=True, null=True)),
                ('rango_tabla', models.CharField(blank=True, max_length=100)),
                ('intentos', models.PositiveSmallIntegerField(default=0)),
                ('procesamiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generaciones', to='procesamientos.procesamientodimanno')),
                ('solicitado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generaciones_dimanno_solicitadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-solicitado_en'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('estado__in', ['pendiente', 'procesando'])), fields=('procesamiento',), name='uniq_generacion_dimanno_activa_por_procesamiento')],
            },
        ),
    ]
