# Generated by Django 5.2.16 on 2026-07-29 16:29

import django.db.models.deletion
import procesamientos.models
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procesamientos', '0004_generacion_dimanno'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GastoProcesamientoMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=40)),
                ('nombre', models.CharField(max_length=100)),
                ('orden', models.PositiveSmallIntegerField()),
                ('valor_original', models.DecimalField(decimal_places=6, max_digits=18)),
                ('valor_aplicado', models.DecimalField(decimal_places=6, max_digits=18)),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='CorreccionGastoMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_anterior', models.DecimalField(decimal_places=6, max_digits=18)),
                ('valor_nuevo', models.DecimalField(decimal_places=6, max_digits=18)),
                ('motivo', models.TextField()),
                ('usuario_nombre', models.CharField(max_length=150)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('gasto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correcciones', to='procesamientos.gastoprocesamientomaster')),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='ProcesamientoMaster',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('anio', models.PositiveIntegerField(default=0)),
                ('factura_corta', models.CharField(max_length=20)),
                ('semana', models.PositiveIntegerField(default=0)),
                ('semana_texto', models.CharField(blank=True, max_length=20)),
                ('estado', models.CharField(max_length=40)),
                ('destino_final', models.CharField(blank=True, max_length=150)),
                ('origen_destino_final', models.CharField(blank=True, max_length=30)),
                ('destinos_despachos', models.JSONField(blank=True, default=list)),
                ('cantidad_contenedores', models.PositiveIntegerField(default=0)),
                ('total_cajas_liquidacion', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=18)),
                ('total_cajas_despachos', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=18)),
                ('puede_escribir', models.BooleanField(default=False)),
                ('errores', models.JSONField(blank=True, default=list)),
                ('advertencias', models.JSONField(blank=True, default=list)),
                ('lineas_preparadas', models.JSONField(blank=True, default=list)),
                ('archivo_despachos', models.FileField(upload_to=procesamientos.models.ruta_archivo_despachos_master)),
                ('archivo_liquidacion', models.FileField(upload_to=procesamientos.models.ruta_archivo_liquidacion_master)),
                ('archivo_cliente', models.FileField(upload_to=procesamientos.models.ruta_archivo_cliente_master)),
                ('creado_por_nombre', models.CharField(blank=True, max_length=150)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procesamientos_master_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
        migrations.AddField(
            model_name='gastoprocesamientomaster',
            name='procesamiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gastos', to='procesamientos.procesamientomaster'),
        ),
        migrations.CreateModel(
            name='GeneracionMaster',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('procesando', 'Procesando'), ('completado', 'Completado'), ('error', 'Error')], default='pendiente', max_length=20)),
                ('solicitado_por_nombre', models.CharField(max_length=150)),
                ('solicitado_en', models.DateTimeField(auto_now_add=True)),
                ('iniciado_en', models.DateTimeField(blank=True, null=True)),
                ('finalizado_en', models.DateTimeField(blank=True, null=True)),
                ('archivo_resultado', models.FileField(blank=True, upload_to=procesamientos.models.ruta_archivo_resultado_generacion_master)),
                ('nombre_descarga', models.CharField(blank=True, max_length=255)),
                ('mensaje_error', models.TextField(blank=True)),
                ('destino_aplicado', models.CharField(max_length=150)),
                ('origen_destino_aplicado', models.CharField(blank=True, max_length=30)),
                ('gastos_aplicados', models.JSONField(default=dict)),
                ('filas_agregadas', models.PositiveIntegerField(blank=True, null=True)),
                ('fila_inicial', models.PositiveIntegerField(blank=True, null=True)),
                ('fila_final', models.PositiveIntegerField(blank=True, null=True)),
                ('rango_tabla', models.CharField(blank=True, max_length=100)),
                ('intentos', models.PositiveSmallIntegerField(default=0)),
                ('solicitado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generaciones_master_solicitadas', to=settings.AUTH_USER_MODEL)),
                ('procesamiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generaciones', to='procesamientos.procesamientomaster')),
            ],
            options={
                'ordering': ['-solicitado_en'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('estado__in', ['pendiente', 'procesando'])), fields=('procesamiento',), name='uniq_generacion_master_activa_por_procesamiento')],
            },
        ),
        migrations.AddConstraint(
            model_name='gastoprocesamientomaster',
            constraint=models.UniqueConstraint(fields=('procesamiento', 'codigo'), name='uniq_gasto_master_procesamiento_codigo'),
        ),
    ]
