# Generated by Django 5.2.16 on 2026-08-04 18:34

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procesamientos', '0008_sifa'),
    ]

    operations = [
        migrations.AddField(
            model_name='procesamientosifa',
            name='resumen_contenedores',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='procesamientosifa',
            name='total_venta_eur',
            field=models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=18),
        ),
    ]
