# Generated by Django 5.2.16 on 2026-08-05 18:00

import django.db.models.deletion
import procesamientos.models
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("procesamientos", "0009_sifa_resumen_contenedores"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MapeoGastoGlamour",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "etiqueta_normalizada",
                    models.CharField(max_length=255, unique=True),
                ),
                (
                    "etiqueta_original",
                    models.CharField(max_length=255),
                ),
                (
                    "columna_destino",
                    models.CharField(max_length=100),
                ),
                (
                    "creado_por_nombre",
                    models.CharField(blank=True, max_length=150),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                (
                    "actualizado_en",
                    models.DateTimeField(auto_now=True),
                ),
            ],
            options={
                "ordering": ["etiqueta_normalizada"],
            },
        ),
        migrations.CreateModel(
            name="ProcesamientoGlamour",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("anio", models.PositiveIntegerField(default=0)),
                (
                    "semana",
                    models.PositiveIntegerField(default=0),
                ),
                (
                    "semana_texto",
                    models.CharField(blank=True, max_length=20),
                ),
                (
                    "factura_corta",
                    models.CharField(blank=True, max_length=20),
                ),
                ("estado", models.CharField(max_length=40)),
                (
                    "destino_final",
                    models.CharField(blank=True, max_length=150),
                ),
                (
                    "origen_destino",
                    models.CharField(blank=True, max_length=30),
                ),
                (
                    "destinos_despachos",
                    models.JSONField(blank=True, default=list),
                ),
                (
                    "cantidad_contenedores",
                    models.PositiveIntegerField(default=0),
                ),
                (
                    "total_cajas_liquidacion",
                    models.DecimalField(
                        decimal_places=6,
                        default=Decimal("0"),
                        max_digits=18,
                    ),
                ),
                (
                    "total_cajas_despachos",
                    models.DecimalField(
                        decimal_places=6,
                        default=Decimal("0"),
                        max_digits=18,
                    ),
                ),
                (
                    "total_venta_eur",
                    models.DecimalField(
                        decimal_places=6,
                        default=Decimal("0"),
                        max_digits=18,
                    ),
                ),
                (
                    "total_gastos_eur",
                    models.DecimalField(
                        decimal_places=6,
                        default=Decimal("0"),
                        max_digits=18,
                    ),
                ),
                (
                    "puede_escribir",
                    models.BooleanField(default=False),
                ),
                (
                    "errores",
                    models.JSONField(blank=True, default=list),
                ),
                (
                    "advertencias",
                    models.JSONField(blank=True, default=list),
                ),
                (
                    "lineas_preparadas",
                    models.JSONField(blank=True, default=list),
                ),
                (
                    "rubros_no_mapeados",
                    models.JSONField(blank=True, default=list),
                ),
                (
                    "resumen_gastos",
                    models.JSONField(blank=True, default=dict),
                ),
                (
                    "archivo_despachos",
                    models.FileField(
                        upload_to=(
                            procesamientos.models
                            .ruta_archivo_despachos_glamour
                        ),
                    ),
                ),
                (
                    "archivo_liquidacion",
                    models.FileField(
                        upload_to=(
                            procesamientos.models
                            .ruta_archivo_liquidacion_glamour
                        ),
                    ),
                ),
                (
                    "archivo_cliente",
                    models.FileField(
                        upload_to=(
                            procesamientos.models
                            .ruta_archivo_cliente_glamour
                        ),
                    ),
                ),
                (
                    "creado_por_nombre",
                    models.CharField(blank=True, max_length=150),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                (
                    "actualizado_en",
                    models.DateTimeField(auto_now=True),
                ),
                (
                    "creado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="procesamientos_glamour_creados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-creado_en"],
            },
        ),
        migrations.CreateModel(
            name="GeneracionGlamour",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente"),
                            ("procesando", "Procesando"),
                            ("completado", "Completado"),
                            ("error", "Error"),
                        ],
                        default="pendiente",
                        max_length=20,
                    ),
                ),
                (
                    "solicitado_por_nombre",
                    models.CharField(max_length=150),
                ),
                (
                    "solicitado_en",
                    models.DateTimeField(auto_now_add=True),
                ),
                (
                    "iniciado_en",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "finalizado_en",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "archivo_resultado",
                    models.FileField(
                        blank=True,
                        upload_to=(
                            procesamientos.models
                            .ruta_archivo_resultado_generacion_glamour
                        ),
                    ),
                ),
                (
                    "nombre_descarga",
                    models.CharField(blank=True, max_length=255),
                ),
                ("mensaje_error", models.TextField(blank=True)),
                (
                    "destino_aplicado",
                    models.CharField(max_length=150),
                ),
                (
                    "origen_destino_aplicado",
                    models.CharField(blank=True, max_length=30),
                ),
                (
                    "filas_agregadas",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                    ),
                ),
                (
                    "fila_inicial",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                    ),
                ),
                (
                    "fila_final",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                    ),
                ),
                (
                    "rango_tabla",
                    models.CharField(blank=True, max_length=100),
                ),
                (
                    "intentos",
                    models.PositiveSmallIntegerField(default=0),
                ),
                (
                    "procesamiento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="generaciones",
                        to="procesamientos.procesamientoglamour",
                    ),
                ),
                (
                    "solicitado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="generaciones_glamour_solicitadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-solicitado_en"],
            },
        ),
        migrations.AddConstraint(
            model_name="generacionglamour",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("estado__in", ["pendiente", "procesando"])
                ),
                fields=("procesamiento",),
                name="uniq_generacion_glamour_activa_por_procesamiento",
            ),
        ),
    ]
