# Generated by Django 5.2.16 on 2026-08-17 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procesamientos', '0013_fruver'),
    ]

    operations = [
        migrations.AddField(
            model_name='procesamientofruver',
            name='factura_corta',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
