# Generated by Django 5.2.16 on 2026-09-07 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procesamientos', '0019_eurobanan'),
    ]

    operations = [
        migrations.AddField(
            model_name='procesamientoorsero',
            name='destinos_indicados',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
