from django.urls import path

from procesamientos import views, views_master

app_name = "procesamientos"

urlpatterns = [
    path(
        "",
        views.panel_control,
        name="panel",
    ),
    path(
        "bitacoras/",
        views.bitacoras,
        name="bitacoras",
    ),
    path(
        "dimanno/",
        views.cargar_dimanno,
        name="dimanno_cargar",
    ),
    path(
        "dimanno/<uuid:procesamiento_id>/",
        views.detalle_dimanno,
        name="dimanno_detalle",
    ),
    path(
        "dimanno/<uuid:procesamiento_id>/gastos/editar/",
        views.editar_gastos_dimanno,
        name="dimanno_gastos_editar",
    ),
    path(
        "dimanno/<uuid:procesamiento_id>/destino/resolver/",
        views.resolver_destino_dimanno,
        name="dimanno_destino_resolver",
    ),
    path(
        "dimanno/<uuid:procesamiento_id>/generar/",
        views.solicitar_generacion_dimanno,
        name="dimanno_generar",
    ),
    path(
        "dimanno/generaciones/<uuid:generacion_id>/",
        views.detalle_generacion_dimanno,
        name="dimanno_generacion_detalle",
    ),
    path(
        (
            "dimanno/generaciones/<uuid:generacion_id>/"
            "descargar/"
        ),
        views.descargar_generacion_dimanno,
        name="dimanno_generacion_descargar",
    ),
    path(
        "master/",
        views_master.cargar_master,
        name="master_cargar",
    ),
    path(
        "master/<uuid:procesamiento_id>/",
        views_master.detalle_master,
        name="master_detalle",
    ),
    path(
        "master/<uuid:procesamiento_id>/gastos/editar/",
        views_master.editar_gastos_master,
        name="master_gastos_editar",
    ),
    path(
        "master/<uuid:procesamiento_id>/generar/",
        views_master.solicitar_generacion_master,
        name="master_generar",
    ),
    path(
        "master/generaciones/<uuid:generacion_id>/",
        views_master.detalle_generacion_master,
        name="master_generacion_detalle",
    ),
    path(
        (
            "master/generaciones/<uuid:generacion_id>/"
            "descargar/"
        ),
        views_master.descargar_generacion_master,
        name="master_generacion_descargar",
    ),
]
