from django.urls import path

from procesamientos import (
    views,
    views_eurobanan,
    views_glamour,
    views_nufri,
    views_kraaijeveld,
    views_master,
    views_orsero,
    views_sifa,
    views_tdv_europa,
    views_fruver,
)

app_name = "procesamientos"

urlpatterns = [
    path(
        "",
        views.panel_control,
        name="panel",
    ),
    path(
        "bitacoras/",
        views.bitacoras,
        name="bitacoras",
    ),
    path(
        "ingresos/",
        views.ingresos,
        name="ingresos",
    ),
    path(
        "dimanno/",
        views.cargar_dimanno,
        name="dimanno_cargar",
    ),
    path(
        "dimanno/<uuid:procesamiento_id>/",
        views.detalle_dimanno,
        name="dimanno_detalle",
    ),
    path(
        "dimanno/<uuid:procesamiento_id>/gastos/editar/",
        views.editar_gastos_dimanno,
        name="dimanno_gastos_editar",
    ),
    path(
        "dimanno/<uuid:procesamiento_id>/destino/resolver/",
        views.resolver_destino_dimanno,
        name="dimanno_destino_resolver",
    ),
    path(
        "dimanno/<uuid:procesamiento_id>/generar/",
        views.solicitar_generacion_dimanno,
        name="dimanno_generar",
    ),
    path(
        "dimanno/generaciones/<uuid:generacion_id>/",
        views.detalle_generacion_dimanno,
        name="dimanno_generacion_detalle",
    ),
    path(
        (
            "dimanno/generaciones/<uuid:generacion_id>/"
            "descargar/"
        ),
        views.descargar_generacion_dimanno,
        name="dimanno_generacion_descargar",
    ),
    path(
        "master/",
        views_master.cargar_master,
        name="master_cargar",
    ),
    path(
        "master/<uuid:procesamiento_id>/",
        views_master.detalle_master,
        name="master_detalle",
    ),
    path(
        "master/<uuid:procesamiento_id>/gastos/editar/",
        views_master.editar_gastos_master,
        name="master_gastos_editar",
    ),
    path(
        "master/<uuid:procesamiento_id>/generar/",
        views_master.solicitar_generacion_master,
        name="master_generar",
    ),
    path(
        "master/generaciones/<uuid:generacion_id>/",
        views_master.detalle_generacion_master,
        name="master_generacion_detalle",
    ),
    path(
        (
            "master/generaciones/<uuid:generacion_id>/"
            "descargar/"
        ),
        views_master.descargar_generacion_master,
        name="master_generacion_descargar",
    ),
    path(
        "orsero/",
        views_orsero.cargar_orsero,
        name="orsero_cargar",
    ),
    path(
        "orsero/<uuid:procesamiento_id>/",
        views_orsero.detalle_orsero,
        name="orsero_detalle",
    ),
    path(
        "orsero/<uuid:procesamiento_id>/gastos/editar/",
        views_orsero.editar_gastos_orsero,
        name="orsero_gastos_editar",
    ),
    path(
        "orsero/<uuid:procesamiento_id>/generar/",
        views_orsero.solicitar_generacion_orsero,
        name="orsero_generar",
    ),
    path(
        "orsero/generaciones/<uuid:generacion_id>/",
        views_orsero.detalle_generacion_orsero,
        name="orsero_generacion_detalle",
    ),
    path(
        (
            "orsero/generaciones/<uuid:generacion_id>/"
            "descargar/"
        ),
        views_orsero.descargar_generacion_orsero,
        name="orsero_generacion_descargar",
    ),
    path(
        "kraaijeveld/",
        views_kraaijeveld.cargar_kraaijeveld,
        name="kraaijeveld_cargar",
    ),
    path(
        "kraaijeveld/<uuid:procesamiento_id>/",
        views_kraaijeveld.detalle_kraaijeveld,
        name="kraaijeveld_detalle",
    ),
    path(
        "kraaijeveld/<uuid:procesamiento_id>/generar/",
        views_kraaijeveld.solicitar_generacion_kraaijeveld,
        name="kraaijeveld_generar",
    ),
    path(
        "kraaijeveld/generaciones/<uuid:generacion_id>/",
        views_kraaijeveld.detalle_generacion_kraaijeveld,
        name="kraaijeveld_generacion_detalle",
    ),
    path(
        (
            "kraaijeveld/generaciones/<uuid:generacion_id>/"
            "descargar/"
        ),
        views_kraaijeveld.descargar_generacion_kraaijeveld,
        name="kraaijeveld_generacion_descargar",
    ),
    path(
        "sifa/",
        views_sifa.cargar_sifa,
        name="sifa_cargar",
    ),
    path(
        "sifa/<uuid:procesamiento_id>/",
        views_sifa.detalle_sifa,
        name="sifa_detalle",
    ),
    path(
        "sifa/<uuid:procesamiento_id>/generar/",
        views_sifa.solicitar_generacion_sifa,
        name="sifa_generar",
    ),
    path(
        "sifa/generaciones/<uuid:generacion_id>/",
        views_sifa.detalle_generacion_sifa,
        name="sifa_generacion_detalle",
    ),
    path(
        (
            "sifa/generaciones/<uuid:generacion_id>/"
            "descargar/"
        ),
        views_sifa.descargar_generacion_sifa,
        name="sifa_generacion_descargar",
    ),
    path(
        "glamour/",
        views_glamour.glamour_cargar,
        name="glamour_cargar",
    ),
    path(
        "eurobanan/",
        views_eurobanan.eurobanan_cargar,
        name="eurobanan_cargar",
    ),
    path(
        "eurobanan/<uuid:procesamiento_id>/",
        views_eurobanan.eurobanan_validacion,
        name="eurobanan_validacion",
    ),
    path(
        "eurobanan/<uuid:procesamiento_id>/mapear-gastos/",
        views_eurobanan.eurobanan_mapear_gastos,
        name="eurobanan_mapear_gastos",
    ),
    path(
        "eurobanan/<uuid:procesamiento_id>/generar/",
        views_eurobanan.eurobanan_generar,
        name="eurobanan_generar",
    ),
    path(
        "eurobanan/generaciones/<uuid:generacion_id>/",
        views_eurobanan.eurobanan_generacion_detalle,
        name="eurobanan_generacion_detalle",
    ),
    path(
        (
            "eurobanan/generaciones/<uuid:generacion_id>/"
            "descargar/"
        ),
        views_eurobanan.eurobanan_generacion_descargar,
        name="eurobanan_generacion_descargar",
    ),
    path(
        "glamour/<uuid:procesamiento_id>/",
        views_glamour.glamour_validacion,
        name="glamour_validacion",
    ),
    path(
        "glamour/<uuid:procesamiento_id>/mapear-gastos/",
        views_glamour.glamour_mapear_gastos,
        name="glamour_mapear_gastos",
    ),
    path(
        "glamour/<uuid:procesamiento_id>/generar/",
        views_glamour.glamour_generar,
        name="glamour_generar",
    ),
    path(
        "glamour/generaciones/<uuid:generacion_id>/",
        views_glamour.glamour_generacion_detalle,
        name="glamour_generacion_detalle",
    ),
    path(
        (
            "glamour/generaciones/<uuid:generacion_id>/"
            "descargar/"
        ),
        views_glamour.glamour_generacion_descargar,
        name="glamour_generacion_descargar",
    ),
    path(
        "nufri/",
        views_nufri.nufri_cargar,
        name="nufri_cargar",
    ),
    path(
        "nufri/<uuid:procesamiento_id>/",
        views_nufri.nufri_validacion,
        name="nufri_validacion",
    ),
    path(
        "nufri/<uuid:procesamiento_id>/mapear-gastos/",
        views_nufri.nufri_mapear_gastos,
        name="nufri_mapear_gastos",
    ),
    path(
        "nufri/<uuid:procesamiento_id>/generar/",
        views_nufri.nufri_generar,
        name="nufri_generar",
    ),
    path(
        "nufri/generaciones/<uuid:generacion_id>/",
        views_nufri.nufri_generacion_detalle,
        name="nufri_generacion_detalle",
    ),
    path(
        (
            "nufri/generaciones/<uuid:generacion_id>/"
            "descargar/"
        ),
        views_nufri.nufri_generacion_descargar,
        name="nufri_generacion_descargar",
    ),
    path(
        "tdv-europa/",
        views_tdv_europa.tdv_europa_cargar,
        name="tdv_europa_cargar",
    ),
    path(
        "tdv-europa/<uuid:procesamiento_id>/",
        views_tdv_europa.tdv_europa_validacion,
        name="tdv_europa_validacion",
    ),
    path(
        "tdv-europa/<uuid:procesamiento_id>/generar/",
        views_tdv_europa.tdv_europa_generar,
        name="tdv_europa_generar",
    ),
    path(
        "tdv-europa/generaciones/<uuid:generacion_id>/",
        views_tdv_europa.tdv_europa_generacion_detalle,
        name="tdv_europa_generacion_detalle",
    ),
    path(
        (
            "tdv-europa/generaciones/<uuid:generacion_id>/"
            "descargar/"
        ),
        views_tdv_europa.tdv_europa_generacion_descargar,
        name="tdv_europa_generacion_descargar",
    ),
    path(
        "fruver/",
        views_fruver.cargar_fruver,
        name="fruver_cargar",
    ),
    path(
        "fruver/<uuid:procesamiento_id>/",
        views_fruver.detalle_fruver,
        name="fruver_detalle",
    ),
    path(
        "fruver/<uuid:procesamiento_id>/generar/",
        views_fruver.solicitar_generacion_fruver,
        name="fruver_generar",
    ),
    path(
        "fruver/generaciones/<uuid:generacion_id>/",
        views_fruver.detalle_generacion_fruver,
        name="fruver_generacion_detalle",
    ),
    path(
        (
            "fruver/generaciones/<uuid:generacion_id>/"
            "descargar/"
        ),
        views_fruver.descargar_generacion_fruver,
        name="fruver_generacion_descargar",
    ),
]
